config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("users/", include("users.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
   path("", views.ProductListView.as_view()),
   path("products/", views.ProductsListView.as_view()),####
   path("contacts/", views.ContactView.as_view()),
   path("product/<int:pk>/", views.ProductDetailView.as_view(), name='product'),
   path("blog/", views.BlogsListView.as_view(), name='blog_list'),
   path("blog/<int:pk>/", views.BlogsDetailView.as_view(), name='view'),
   path("blog/create/", views.BlogsCreateView.as_view(), name='blog_from'),
   path("blog/update/<int:pk>/", views.BlogsUpdateView.as_view()),
   path("blog/delete/<int:pk>/", views.BlogsDeleteView.as_view()),
   path("create/", views.ProductCreateView.as_view()),
   path("delete/<int:pk>/", views.ProductDeleteView.as_view()),
   path("update/<int:pk>/", views.ProductUpdateView.as_view()),
   path("version/delete/<int:pk>/", views.VersionDeleteView.as_view()),
   path("version/update/<int:pk>/", views.VersionUpdateView.as_view())
]     

main/models.py
from django.db import models
from users.models import User

NULLABLE = {'null':True, 'blank':True}

class Product(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   name = models.CharField(max_length=100, verbose_name='Название')
   description = models.TextField(verbose_name='Описание')
   preview = models.ImageField(upload_to='products/', **NULLABLE)
   category = models.CharField(max_length=100, verbose_name='Категория')
   purchase_price = models.IntegerField(verbose_name='Цена за покупку')
   date_of_creation = models.TimeField(verbose_name='дата создания',**NULLABLE)
   last_modified_date = models.TimeField(verbose_name='дата последнего изменения',**NULLABLE)
   number_of_views = models.IntegerField(verbose_name='Просмотры', **NULLABLE, default=0)
   is_active = models.BooleanField(default=True, verbose_name='Активен')
   
   def __str__(self):
      return f'{self.name} {self.description} {self.category} {self.purchase_price} {self.date_of_creation} {self.last_modified_date}' 
   
   class Meta:
      verbose_name = 'Продукт'
      verbose_name_plural = 'Продукты'
      ordering = ('name',)

class Category(models.Model):
   name = models.CharField(max_length=100, verbose_name='Название')
   description = models.TextField(verbose_name='Описание')
   created_at = models.TimeField(verbose_name='дата создания', **NULLABLE)

   def __str__(self):
      return f'{self.name} {self.description}' 

   class Meta:
      verbose_name = 'Категория'
      verbose_name_plural = 'Категории'
      ordering = ('name',)

class Blog(models.Model):
   header = models.CharField(max_length=100, verbose_name='заголовок')
   slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
   content = models.CharField(max_length=250, verbose_name='Cодержимое')
   preview = models.ImageField(upload_to='blogs/', **NULLABLE, verbose_name='превью ')
   date_creation = models.TimeField(verbose_name='Дата создания', **NULLABLE)
   is_publication = models.BooleanField(verbose_name='Опубликовано')
   number_of_views = models.IntegerField(verbose_name='Просмотры', **NULLABLE, default=0)

   def __str__(self):
      return f'{self.header} {self.slug} {self.content} {self.date_creation} {self.is_publication} {self.number_of_views}' 
   
   class Meta:
      verbose_name = 'Статья'
      verbose_name_plural = 'Статьи'
      ordering = ('header',)

class Version(models.Model):
   version_number =  models.IntegerField(verbose_name='Номер версии')
   version_name =  models.CharField(max_length=100, verbose_name='Название версии')
   is_active_version = models.BooleanField(verbose_name='Признак версии')
   product = models.ForeignKey(Product, related_name='version', on_delete=models.CASCADE)
   
   def __str__(self):
      return f'{self.version_number} {self.version_name} {self.is_active_version} {self.product}' 
   
   class Meta:
      verbose_name = 'Версия'
      verbose_name_plural = 'Версии'
      ordering = ('version_number',)

main/forms.py
from django import forms
from main.models import Product, Version

class StyleFormMixin:
   def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      for field_name, field in self.fields.items():
         field.widget.attrs['class'] = 'form-control'

class ProductForm(forms.ModelForm):

   class Meta:
      model = Product 
      fields = '__all__'
   
   def clean(self):
      cleaned_data = super().clean()
      name = cleaned_data.get('name')
      forbidden_products = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар'] 

      description = cleaned_data.get('description')
      forbidden_products = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

      if name.lower() in forbidden_products:
         self.add_error('name', "Вы не можете в поле 'Название' создавать товары с запрещенным названием.")
        
      if description.lower() in forbidden_products:
         self.add_error('description', "Вы не можете в поле 'Описание' создавать товары с запрещенным описанием.")


class VersionForm(forms.ModelForm):

   class Meta:
      model = Version
      fields = '__all__'

main/views.py
from typing import Any, Dict
from django.conf import settings
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView , View, CreateView, UpdateView, DeleteView
from main.forms import ProductForm, VersionForm
from main.models import Blog, Product, Version
from pytils.translit import slugify
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from main.permissions import AuthorPermissionsMixin, ModeratorPermissionsMixin
from main.services import get_cached_subjects_for_product

class ContactView(View):
   template_name = 'main/contacts.html'

   def get(self, request):
      return render(request, self.template_name)

   def post(self, request):
      name = request.POST.get("name")
      phone = request.POST.get("phone")
      message = request.POST.get("message")
      print(f"name: {name}, phone: {phone}, message: {message}")
      return render(request, self.template_name)
   
#----------------------------------------------------------------------
@method_decorator(login_required, name='dispatch')
class BlogsListView(ListView):
   model = Blog

   def get_queryset(self):
      return Blog.objects.filter(is_publication=True)

@method_decorator(login_required, name='dispatch')
class BlogsDetailView(DetailView):
   model = Blog

   def get_object(self, queryset=None):
      self.object = super().get_object(queryset)
      self.object.number_of_views += 1
      self.object.save()
      return self.object

@method_decorator(login_required, name='dispatch')   
class BlogsCreateView(CreateView):
   model = Blog
   fields = ('header', 'slug', 'content', 'preview', 'date_creation', 'is_publication', 'number_of_views')
   success_url = '/blog/' 

   def form_valid(self, form):
      if form.is_valid():
         new_mat = form.save()
         new_mat.slug = slugify(new_mat.header)
         new_mat.save
         
      return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class BlogsUpdateView(UpdateView):
   model = Blog
   fields = ('header', 'slug', 'content', 'preview', 'date_creation', 'is_publication', 'number_of_views')
   success_url = '/blog/' 

   def form_valid(self, form):
      if form.is_valid():
         new_mat = form.save()
         new_mat.slug = slugify(new_mat.header)
         new_mat.save

      return super().form_valid(form)
   
   def get_success_url(self):
      return reverse('main:view', args=[self.kwargs.get('pk')])

@method_decorator(login_required, name='dispatch')
class BlogsDeleteView(DeleteView):
   model = Blog
   success_url = '/blog/' 

#----------------------------------------------------------------------
@method_decorator(login_required, name='dispatch')
class ProductCreateView(CreateView):
   model = Product 
   form_class = ProductForm
   success_url = '/' 

@method_decorator(login_required, name='dispatch')
class ProductDeleteView(AuthorPermissionsMixin, DeleteView):
   model = Product
   success_url = '/' 

@method_decorator(login_required, name='dispatch')
class ProductListView(ListView):
   model = Product
   
@method_decorator(login_required, name='dispatch')
class ProductDetailView(ModeratorPermissionsMixin, DetailView):
   model = Product

   def get_object(self, queryset=None):
      self.object = super().get_object(queryset)
      self.object.number_of_views += 1
      self.object.save()
      return self.object

   def get_context_data(self, **kwargs):
      context_data = super().get_context_data(**kwargs)
      subject_list = get_cached_subjects_for_product(self.object.pk)
      context_data['subjects'] = subject_list
      return context_data

@method_decorator(login_required, name='dispatch')   
class ProductUpdateView(ModeratorPermissionsMixin, UpdateView):
   model = Product
   form_class = ProductForm
   success_url = '/'

   def get_success_url(self):
      return reverse('main:product', args=[self.kwargs.get('pk')])

   def get_context_data(self, **kwargs):
      context_data = super().get_context_data(**kwargs)
      is_moder = self.request.user.groups.filter(name='moderator').exists()
      is_owner = self.get_object().user == self.request.user
      while True:
         if is_owner:
            break
         
         elif is_moder:
            context_data['is_moderator'] = is_moder
            break
         
      VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

      if self.request.method == 'POST':
         context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
      else:
         context_data['formset'] = VersionFormset(instance=self.object)

      return context_data

   def form_valid(self, form):
      formset = self.get_context_data()['formset']
      self.object = form.save()

      if formset.is_valid():
         formset.instance = self.object
         formset.save()

      return super().form_valid(form)
   
#----------------------------------------------------------------------
@method_decorator(login_required, name='dispatch')
class ProductsListView(ListView):
   model = Product
   template_name = 'main/products_list.html'

#-------------------------------------------------------------
@method_decorator(login_required, name='dispatch')
class VersionUpdateView(UpdateView):
   model = Version 
   form_class = VersionForm
   success_url = '/' 

@method_decorator(login_required, name='dispatch')
class VersionDeleteView(DeleteView):
   model = Version
   success_url = '/' 

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Sky</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>
  
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white"></h4>
              <ul class="list-unstyled">
                {% if user.is_authenticated %}
                  <li>
                    <details><summary class="text-white">Профиль</summary>
                      <a  class="text-white" href="http://127.0.0.1:8000/users/profile/">Открыть профиль</a>
                      <br>
                      <a class="text-white" href="http://127.0.0.1:8000/users/logout/">Выйти</a>
                    </details>
                  </li> 
                  <li><a href="http://127.0.0.1:8000/contacts/" class="text-white">Контакты</a></li>
                <li><a href="http://127.0.0.1:8000/blog/" class="text-white">Статьи</a></li>
                
                {% else %}
                  <li>
                    <details><summary class="text-white">Здравствуй, гость</summary>
                      <a  class="text-white" href="http://127.0.0.1:8000/users/login/">Войти</a>, <a class="text-white" href="http://127.0.0.1:8000/users/register">Зарегистрироватся</a>
                    </details>
                  </li>   
                  <li><a href="http://127.0.0.1:8000/contacts/" class="text-white">Контакты</a></li>
                {% endif %} 
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="http://127.0.0.1:8000/" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">
      
      <section class="jumbotron text-center">
        
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
          
          <div class="row">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="/">Back to home</a>
        </p>
        <p>&copy; 2023</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>

main/templates/main/blog_confirm_delete.html
{% extends 'main/base.html' %} 
{% block content %} 

<div class="col-12">
   <div class="row">
      <div class="col-6">
         <div class="card">
            <div class="card-body">
               <form method="post">
                  {% csrf_token %}
                  <p>Хотите удалить статью: {{ object.header }}</p>
                  <button type="submit" class="btn btn-danger">Подтвердить</button>
                  <a href="/blog" class="btn btn-warning">Отмена</a>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>

{% endblock %} 

main/templates/main/blog_detail.html
{% extends 'main/base.html' %} 
{% block content %} 
<div class="col-md-4">
   <div class="card mb-4 box-shadow">
    {% if object.preview %}
        <img class="card-img-top" src="{{ object.preview.url }}" alt="{{ object.header }}" style="height: 225px; width: 100%; display: block;"/>
    {% else %}
     {% endif %} 
        <div class="card-body">
       <p class="card-text">Заголовок: {{object.header}} ({{object.slug}})</p> 
       <p class="card-text">Cодержимое: {{object.content}}</p>
       <p class="card-text">Дата создания: {{object.date_creation}}</p>
       <p class="card-text">Опубликовано: {{object.is_publication}}</p> 
       <p class="card-text">Просмотры: {{object.number_of_views}}</p>
       <div class="d-flex justify-content-between align-items-center">
         <div class="btn-group">
           <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location.href='/blog/update/{{ object.pk }}'">Edit</button>
           <button type="button" class="btn btn-danger" onclick="window.location.href='/blog/delete/{{ object.pk }}'">Delete</button>
         </div>
       </div>
     </div>
   </div> 
 </div>
 

{% endblock %} 

main/templates/main/blog_form.html
{% extends 'main/base.html' %} 
{% block content %} 
<form method="POST" enctype="multipart/form-data">
   {% csrf_token %}
   <div class="form-group has-success">
     <label class="control-label" for="inputSuccess1">Заголовок</label>
     <input type="name" name="header" class="form-control" id="inputSuccess1">
   </div>
   <div class="form-group has-error">
     <label class="control-label" for="inputError1">Cодержимое</label>
     <input type="message" name="content" class="form-control" id="inputError1">
   </div>
   <div class="form-group has-success">
      <label class="control-label" for="inputSuccess1">Превью:</label>
      <input type="file" name="preview" id="fileInput" accept="image/*">
    </div>
    <div class="form-group has-warning">
      <label class="control-label" for="inputWarning1">Дата создания</label>
      <input type="time" name="date_creation" class="form-control" id="inputWarning1">
    </div>
    <div class="form-group has-error">
      <label class="control-label" for="inputError1">Опубликовано</label>
      <br>
      <input type="radio" name="is_publication" value="1"> Да
      <input type="radio" name="is_publication" value="Нет"> Нет
    </div>
   <div class="form-group has-error">
      <label class="control-label" for="inputError1"></label>
      <input type="submit" class="btn btn-primary" id="inputError1">
 </form>
{% endblock %} 

main/templates/main/blog_list.html
{% extends 'main/base.html' %} 
{% block content %} 
   
   <input onclick="window.location.href='/blog/create/'" class="btn btn-success mb-4" type="submit" value="Добавить статью" id="add-article-btn" style="position: absolute; top: 28%; left: 18%;">
   
   {% for object in object_list %}
         <div class="col-md-4">
            <div class="card mb-4 box-shadow">
            <div class="card-body">
               <p class="card-text">Название: {{object.header}}</p>
               <p class="card-text">Описание: {{object.content|truncatechars:100}}</p>
               <div class="d-flex justify-content-between align-items-center">
               <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location.href='/blog/{{ object.pk }}/'">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location.href='/blog/update/{{ object.pk }}'">Edit</button>
                  <button type="button" class="btn btn-danger" onclick="window.location.href='/blog/delete/{{ object.pk }}'">Delete</button>
               </div>
               </div>
            </div>
         
         </div>
         </div>
         <style>
            .btn{
               float: left;
            }
            .card-body  {
               
               height:230px;
            }
         </style>
   {% endfor %}
{% endblock %} 

main/templates/main/contacts.html
{% extends 'main/base.html' %} 
{% block content %} 

<div class="col-6">
   Офис в Крыму<br>
   Офис в Москве<br>
   Офис в Питере
</div>
<form method = 'POST'>
   {% csrf_token %}
   <div class="form-group has-success">
     <label class="control-label" for="inputSuccess1">Имя</label>
     <input type="name" name="name" class="form-control" id="inputSuccess1">
   </div>
   <div class="form-group has-warning">
     <label class="control-label" for="inputWarning1">Телефон</label>
     <input type="phone" name="phone" class="form-control" id="inputWarning1">
   </div>
   <div class="form-group has-error">
     <label class="control-label" for="inputError1">Сообщение</label>
     <input type="message" name="message" class="form-control" id="inputError1">
   </div>
   <div class="form-group has-error">
      <label class="control-label" for="inputError1"></label>
      <input type="submit" class="btn btn-primary" id="inputError1">
 </form>
{% endblock %} 

main/templates/main/index.html
{% extends 'main/base.html' %}     
{% block content %}       
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">Название: {{object.name}}</p>
                  <p class="card-text">Описание: {{object.description}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
{% endblock %}

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html' %} 
{% block content %} 

<div class="col-12">
   <div class="row">
      <div class="col-6">
         <div class="card">
            <div class="card-body">
               <form method="post">
                  {% csrf_token %}
                  <p>Хотите удалить продукт?: {{ object }}</p>
                  <button type="submit" class="btn btn-danger">Подтвердить</button>
                  <a href="/" class="btn btn-warning">Отмена</a>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>

{% endblock %}    

main/templates/main/product_form.html
{% extends 'main/base.html' %} 
{% block content %} 
<div class="col-12">
   <form method="POST" enctype="multipart/form-data">
      <div class="col-6">
         <div class="card">
            <div class="card-header">
                <h2 class="card-title">
                  Продукт
               </h2>
            </div>
            <div class="card-header">
               {% csrf_token %}
               <style>
                  .errors {
                     color: red; 
                     font-weight: bold; 
                  }
               </style>
               {% if form.errors %}
               <div class="errors">
                  <ul>
                     {% for field_name, errors in form.errors.items %}
                        {% for error in errors %}
                              <li>{{ error }}</li>
                        {% endfor %}
                     {% endfor %}
                  </ul>
               </div>
               {% endif %}
               {% if is_moderator %}
               <!-- Поля доступные для модераторов -->
                  <label class="control-label" for="inputError1">Описание</label>
                  <input type="message" name="description" class="form-control" id="inputError1" value='{{ object.description }}'>
                  <label class="control-label" for="inputWarning1">Категория</label>
                  <input type="name" name="category" class="form-control" id="inputWarning1" value='{{ object.category }}'>
                  <br>
                  <label class="control-label mb-2" for="inputError1">Активен</label>
                  <select name="is_active">
                     <option value="True">Да</option>
                     <option value="False">Нет</option>
                 </select>
                 <br>
                 <label class="control-label" for="inputError1">Цена за покупку</label>
                  <input type="number" name="purchase_price" value="{{ object.purchase_price }}" {% if is_moderator %}readonly{% endif %}>
                  <br>
                  <label class="control-label " for="inputError1">Дата создания</label>
                  <input type="time" name="date_of_creation" value="{{ object.date_of_creation }}" readonly>
                  <br>
                  <label class="control-label" for="inputError1">Дата последнего изменения</label>
                  <input type="time" name="last_modified_date" value="{{ object.last_modified_date }}" readonly>
                  <br>
                  <label class="control-label" for="inputSuccess1">Название</label>
                  <input type="name" name="name" class="form-control" id="inputSuccess1" value="{{ object.name }}" readonly>
                  <br>
                  <input type="submit" class="btn btn-primary" id="inputError1">
               {% else %}
               <div class="card-body">
                  <label class="control-label" for="inputSuccess1">Название</label>
                  <input type="name" name="name" class="form-control" id="inputSuccess1" value='{{ object.name }}'>

                  <label class="control-label" for="inputError1">Описание</label>
                  <input type="message" name="description" class="form-control" id="inputError1" value='{{ object.description }}'>
                  <br>
                  <label class="control-label mb-2" for="inputSuccess1">Превью:</label>
                  <input type="file" name="preview" id="fileInput" accept="image/*" value='{{ object.preview }}'>
                     <br>
                  <label class="control-label" for="inputWarning1">Категория</label>
                  <input type="name" name="category" class="form-control" id="inputWarning1" value='{{ object.category }}'>
                     <br>
                  <label class="control-label" for="inputError1">Цена за покупку</label>
                  <input type="number" name="purchase_price" value='{{ object.purchase_price }}'>
                     <br>
                  <label class="control-label " for="inputError1">Дата создания</label>
                  <input type="time" name="date_of_creation" value='{{ object.date_of_creation }}'> 
                  <br>
                  <label class="control-label" for="inputError1">Дата последнего изменения</label>
                  <input type="time" name="last_modified_date" value='{{ object.last_modified_date }}'>
                  <br>
                  <label class="control-label" for="inputError1">Активен</label>
                  <select name="is_active">
                     <option value="True">Да</option>
                     <option value="False">Нет</option>
                 </select>
                 <br>
                 <label class="required" for="id_user">User:</label>                             
                  <div class="related-widget-wrapper" data-model-ref="пользователь">
                     <select name="user" required id="id_user">
                     <option value="">---------------------------</option>
                     <option value="{{ user.pk }}">{{ user }}</option>
                     </select>
                  </div>  
                  <br>
               <input type="submit" class="btn btn-primary" id="inputError1">   
              </div>
            </div>   
         </div>      
      </div>
      <div style="position: absolute; top: 0; right: 0;">
         <div class="card">
            <div class="card-header">
               <h2 class="card-title">
                  Версии продукта
               </h2>
            </div>
            <div class="card-body">
               {{ formset.management_form }}
               {% for form in formset.forms %}
                  {{ form.as_p }}
                  <hr>
               {% endfor %}
            </div>
         </div>
      </div>
   </form>
</div>
{% endif %}

{% endblock %} 

main/templates/main/product_list.html
{% extends 'main/base.html' %}     
{% block content %}
  
<input onclick="window.location.href='/create'" class="btn btn-success mb-4" type="submit" value="Добавить продукт" id="add-article-btn" style="position: absolute; top: 28%; left: 18.3%;">
   
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text">Название: {{object.name}}</p>
                  <p class="card-text">Описание: {{object.description|truncatechars:100}}</p>
                  <p class="card-text">Цена: {{object.purchase_price}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button onclick="window.location.href='/product/{{object.pk}}/'" type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button onclick="window.location.href='/update/{{object.pk}}/'" type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                      <button onclick="window.location.href='/delete/{{object.pk}}/'" type="button" class="btn btn-danger">Delete</button>
                    </div>
                  </div>
                </div>
              </div>
              <style>
                .btn{
                   float: left;
                }
                .card-body  {
                   
                   height:230px;
                }
             </style>
            </div>
            {% endfor %}
{% endblock %}

main/templates/main/products.html
{% extends 'main/base.html' %}     
{% block content %}       
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
               <img src="/media/{{ object.preview }}" style="height: 225px; width: 100%; display: block;"/>
                <div class="card-body">
                  <p class="card-text">Название: {{object.name}}</p> 
                  <p class="card-text">Описание: {{object.description}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
{% endblock %}